### ISSUE TITLE
psharpen expr needs to be fixed

### ISSUE THREAD

**Issue by theChaosCoder** [Vapoursynth-Plugins-Gitify/G41Fun#2]
Unprotected div... expr = 'x y / ...'

https://github.com/Vapoursynth-Plugins-Gitify/G41Fun/blob/baad3ee1f47a5ed0b8526bef083b938f900a0bc7/G41Fun.py#L192

https://github.com/vapoursynth/vapoursynth/issues/780

**Comment by theChaosCoder** [comment]
"Fixed" by switching to akarin.Expr() plugin for now.

If someone can properly fix the expression line, pls do.

**Comment by theChaosCoder** [comment]
Fixed by https://github.com/Vapoursynth-Plugins-Gitify/G41Fun/pull/4

**Comment by AkarinVS** [comment]
The reason for the difference in behavior of `std.Expr` and `akarin.Expr` is that they clamp `nan` (when the expression computes `0/0` it generates `nan`) differently.
- `std.Expr` would clamp it to the maximum value for the output format, hence the bright white dot
- `akarin.Expr` would clamp it to the minimum value for the output format, which happens to be what the expression wants.

**Comment by theChaosCoder** [comment]
Ah good to know. Thx for the explanation.
